import jwt from "jsonwebtoken";
import fs from "fs";
import path from "path";

function generateJwt(id: string, nonce: string): string {
  const privateKey = fs.readFileSync(
    path.join(process.cwd(), "private_key.pem"),
    "utf8"
  );
  const token = jwt.sign({ id, sid: nonce }, privateKey, {
    issuer: "friend-fries",
    expiresIn: "1h",
    algorithm: "RS256",
    subject: id,
  });

  return token;
}

export async function GET(request: Request) {
  // TODO: generate nonce
  // TODO: verify signature you receive
  request.json();
  return Response.json(
    {
      jwt: generateJwt("the id generated by signature", "nonce"),
    },
    { headers: { "Access-Control-Allow-Origin": "*" } }
  );
}
